package pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated 2 dic 2022 13:43:07 by Hibernate Tools 6.1.3.Final

/**
 * Zoologicos generated by hbm2java
 */
@Entity
@Table(name="zoologicos")
public class Zoologico implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="id")
	private int id;
	@Column(name="nombre",nullable=false,unique=true,length=40)
	private String nombre;
	@Column(name="ciudad",nullable=false,length=40)
	private String ciudad;
	@Column(name="anyo_fundacion",nullable=false)
	private int anyoFundacion;

	public Zoologico() {
	}

	public Zoologico(String nombre, String ciudad, int anyoFundacion) {
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnyoFundacion() {
		return this.anyoFundacion;
	}

	public void setAnyoFundacion(int anyoFundacion) {
		this.anyoFundacion = anyoFundacion;
	}

}
